### ISSUE TITLE
No matching entry found with Agenda since Thunderbird 52.1.0

### ISSUE THREAD

**Issue by crazy-max** [kee-org/KeeFox#779] opened 2017-05-04 07:33 UTC
Hi,

Windows 10 64-bits
Keepass 2.35
Thunderbird 52.1.0
Keefox 1.6.4

I can't make things work only with the Agenda prompt for login/password since Thunderbird 52.1.0.

**Comment by dlech** [comment] 2017-05-04 16:34
Can you post a screen shot? Might be a duplicate of #746.

**Comment by crazy-max** [comment] 2017-05-04 16:45
Sure :

![image](https://cloud.githubusercontent.com/assets/1951866/25714876/c53cb260-30f9-11e7-97aa-080a0b0c90fc.png)

**Comment by gigxy** [comment] 2017-05-04 19:32
i ve got firefox 53b09 and with all authentification box doesn't work, same like above, i tried many many version of firefox, nothing, is working 
Keepas and keefox are good configured, the plug is actif
I don't know what to do
I looked up #720, #709,##746

Thanks in advance

**Comment by dlech** [comment] 2017-05-04 19:41
The fix for #746 has not been released yet.

**Comment by crazy-max** [comment] 2017-05-04 21:08
@dlech This PR #776 ?

**Comment by crazy-max** [comment] 2017-05-04 21:20
Confirmed, it works with PR #776 !

**Comment by gigxy** [comment] 2017-05-04 21:27
i don't try, i don't know how to do

**Comment by crazy-max** [comment] 2017-05-04 21:33
@gigxy

* Close Thunderbird or Firefox
* Copy the content of this Pastebin i have created : https://pastebin.com/0RKu2r83 in `PATH_TO_YOUR_PROFILE\profile\extensions\keefox@chris.tomlinson\chrome\content\commonDialog.js`

**Comment by gigxy** [comment] 2017-05-04 22:06
thanks for help ;)
i tried but firefox disable keefox !

**Comment by dlech** [comment] 2017-05-04 22:08
Firefox requires signed addons, so this will only work with Thunderbird or the developer version of Firefox with addon signing disabled.

**Comment by crazy-max** [comment] 2017-05-24 12:38
Hi, what is the next milestone including a fix for this issue ? 1.7.x ? 1.6.x ?
Thanks

**Comment by dlech** [comment] 2017-05-24 17:17
https://github.com/kee-org/KeeFox/releases/tag/v1.7.0b1

**Closed** 2017-10-05 23:35 UTC
