### ISSUE TITLE
KeeFox icon in Firefox stay disabled

### ISSUE THREAD

**Issue by FrAllard** [kee-org/KeeFox#592] opened 2015-12-22 12:17 UTC
When I unlock my computer and get it out of sleep and Firefox was still open, the KeppFox icon is disabled (gray'ish square around it with colored icon inside). This mean that my database is closed/locked, then I go head and unlock my database but the icon stay disabled.

Though, the tooltip clearly say "KeeFox enabled" and it also find and fill up my passwords, but there is no way I can click on it to access the KeeFox menu...

If I close and reopen Firefox, everything comes back to normal. It doesn't do that systematically, sometimes I can lock my computer and unlock it and the icon will stay activated, but sometimes it does that.

Note: My Keepass is set to lock the database automatically when I lock my computer.

_The following screenshoot show KeeFox icon disabled while my Keepass database is open_
![KeePass unlocked](https://cloud.githubusercontent.com/assets/1315726/11954961/2719c47c-a87b-11e5-9ee7-cf053b6de2b9.png)

_The following screenshoot show KeeFox icon disabled but clearly working showing it has found login_
![Login found still disabled](https://cloud.githubusercontent.com/assets/1315726/11954970/518fd87c-a87b-11e5-9ebb-86b87890a4c5.png)

**Comment by luckyrat** [comment] 2016-01-09 13:13
Please try with your other add-ons disabled or with a fresh Firefox profile.

The behaviour sounds like a problem with another add-on or even something related to Firefox itself but either way, there's not enough information here for us to reproduce the problem yet.

**Comment by gt945** [comment] 2016-01-09 14:39
I have same issue

**Comment by FrAllard** [comment] 2016-01-10 19:28
I only have adblock plus add-on installed on my Firefox... I'll try with a new profile, but it does that on all my computers although I use Firefox sync so they might replicate the problem among themselves...

**Comment by luckyrat** [comment] 2016-01-24 15:47
Might be worth trying the Firefox Customise... "Restore defaults" option in case something has messed up just that part of the Firefox configuration.

**Comment by oregszun** [comment] 2016-03-02 09:10
Hi,

same annoying issue here. Happens randomly, and when I open a new browser window, it works there (the old stays in stucked state).
Three different machine, three different firefox installation.

Any idea?

**Comment by cwul** [comment] 2016-04-29 07:50
Hi,

Just started to use KeeFox, but unfortunately I'm experiencing the same issue as described above. I usually don't close Firefox and don't shutdown my computer, so it happens regularly that the KeeFox button is "dead". Funnily, when opening a new Firefox window, the functionality works there, but not in the existing window (as described by oregszun). This issue is pretty annoying, a solution would be highly appreciated.

**Comment by cwul** [comment] 2016-05-17 15:37
Update: Seems to be fixed with Firefox 46.0.1. At least it works for me now.

**Comment by ToXinE** [comment] 2017-03-28 08:23
not for me with FF 52.0.1

**Comment by akyag** [comment] 2017-04-02 09:46
same problem in FF 52 for me too

**Comment by DonMcKee** [comment] 2017-04-05 16:36
Same problem here, FF 52.0.2 (32-bit), KeePass 2.35, and KeeFox 1.6.4 on a brand new Dell Win10 laptop.  I first noticed the problem on a "new" FF install, where KeeFox was the only plug-in (I've since installed others).  As previously mentioned, the button functions properly in any newly opened FF windows, or when I restart FF completely.

I'm a long-time KeeFox user, and have never seen this issue before on either of my other systems (Win 7 desktop, Win 10 laptop).  All three are sync'd via FF sync.

-Don

**Closed** 2020-09-05 21:52 UTC
Labels: need info, project-archived
