### ISSUE TITLE
Keefox changed to kee and is now unusable

### ISSUE THREAD

**Issue by Asimov500** [kee-org/KeeFox#823] opened 2017-11-14 15:36 UTC
Keefox suddenly without warning has changed to kee. I had no popup asking me if I wanted to change, but after the change it is not working correctly.

Normally when you click on the icon in firefox a menu comes down showing your all the sites, and a search box. This is now missing.

All I get when I click the icon is Generate new password, Help centre and Options.

I have been using keepass for years, and now it has been made useless.

What can I do to make it work again?

**Comment by auanasgheps** [comment] 2017-11-14 15:47
lol, seriously? You managed to post an issue on Github and you didn't had a look around?
All the things you have experienced are perfectly expected.
Have a look here.
https://forum.kee.pm/t/kee-2-0-features/28

**Comment by Asimov500** [comment] 2017-11-14 17:47
All the features of keepass that I use have now been removed it seems.
So if I have go out of my browser and click on the link in keepass and then go back to the browser then  what is the point of keefox?
I have been telling people for years how good keefox is, but now I am very disappointed.

**Comment by luckyrat** [comment] 2017-11-14 21:11
@Asimov500 , it sounds like you are upset that the search feature has been removed? That was an added convenience feature which I made use of myself from time to time but by no means the primary use-case for KeeFox - as you say, bookmarks can serve as a reasonable alternative, leaving Kee to focus on form filling and submission of passwords.

As described in kee-org/browser-addon#7 (which you should read and contribute to as you see fit) it's not the  number 1 priority for browser integration since there are alternatives available but we'll definitely take on board any feedback from users to help us prioritise future development of Kee.

Unfortunately since we were forced by Mozilla to rewrite most of the add-on in a very short time frame, we've had to prioritise our efforts and I'm sorry if you feel your main use-cases don't align with what we have focussed on so far; the best way to remedy that is to offer constructive feedback in the relevant issue(s) or the new community forum.

I'm closing this issue as a duplicate of kee-org/browser-addon#7 but please do discuss in the [forum ](https://forum.kee.pm)or new repo if there are other issues you want to be addressed.

I understand it can be frustrating when changes seem to be thrust upon you and I've tried to do everything possible over the past year to communicate the coming changes but I hope you understand that we are somewhat beholden to the decisions of Mozilla.

**Closed by luckyrat** 2017-11-14 21:11 UTC
