### ISSUE TITLE
Basic authentication broken on 51 beta

### ISSUE THREAD

**Issue by cypressious** [kee-org/KeeFox#746] opened 2016-12-21 17:53 UTC
Similar to #709, it seems this broken again in the 51 beta, to be precise 51.0b9 but probably also earlier versions.

**Comment by dlech** [comment] 2016-12-21 18:03
It looks like [different patch](https://hg.mozilla.org/mozilla-central/diff/88570c6adbe2/toolkit/locales/en-US/chrome/global/commonDialogs.properties) is applied compared to FireFox 50.

The matching logic in KeeFox starts [here](https://github.com/luckyrat/KeeFox/blob/master/Firefox%20addon/KeeFox/chrome/content/commonDialog.js#L385), so it looks like we are missing `EnterLoginForProxy3`.

So, if this authentication dialog is for a proxy, then this is a new bug. If you are using one of the localizations listed [here](https://github.com/luckyrat/KeeFox/issues/736#issuecomment-262499242), then this is a duplicate of #736. (The fix for #736 has not been release yet).

**Comment by cypressious** [comment] 2016-12-21 18:12
My locale is de (German). I tried the Simple Locale Switcher to change the locale to en-US but the bug persisted.

**Comment by dlech** [comment] 2016-12-21 18:32
I forgot to ask... which KeeFox version are you using?

**Comment by cypressious** [comment] 2016-12-21 18:35
1.6.4

Kirill Rakhman

Am 21.12.2016 19:32 schrieb "David Lechner" <notifications@github.com>:

**Comment by r2evans** [comment] 2017-01-18 19:11
Same symptoms. I'm using locale en-US with no proxies configured. With TB 50.0b3, KeeFox was working with both IMAP and CalDav auth; now with TB 51.0b1, KeeFox works for IMAP but not for CalDav auth requests.

win10_64, TB 51.0beta, KeeFox 1.6.4, KeePassRPC 1.6.4

**Comment by cypressious** [comment] 2017-04-21 08:54
Still broken in 53. Can we expect a fix for this?

**Closed** 2017-04-29 15:18 UTC
