### ISSUE TITLE
KeeFox - Thunderbird - working than not ... 

### ISSUE THREAD

**Issue by zetheroo** [kee-org/KeeFox#686] opened 2016-07-28 14:59 UTC
OS: Windows 10
Have Keepass and Keefox installed and working since the past year or so. 
Three days ago Keefox in Thunderbird seemed to have lost it's connection to Keepass. So I removed Keefox from TB, revoked the authentication token from Keepass for TB, and re-added the Keefox addon to TB. Restarted TB and got the Keepass code (in red) and copy/pasted it - all good - it's working again.

Next day (at some random point in the day) same thing happens and I repeat the "fix". 
I have done this now on two separate machines every day for 3 days/2 days. It's fixed, and then the next day it's broken again.
Using the same Keefox addon for TB on both machines - keefox-1.6.1b1-tb+fx.xpi

**Comment by r2evans** [comment] 2016-07-28 21:21
This is likely a duplicate of #684.

Within the TB extensions directory (something like `~/AppData/Roaming/Thunderbird/Profiles/*.default/extensions/keefox@chris.tomlinson/deps/deps/` you'll see an updated version of `KeePassRPC.plgx`. This file needs to be copied into your instance of KeePass2. Once copied, completely exit out of KeePass, start it up again, and you should notice a temporary pop-up saying it's compiling plugins. After that, it should work.

(Is there were a way for the TB addon to notify the user (a) a newer version is available, and (b) offer to copy the newer one into place given `KeePassRPCCopier.exe`?)

**Comment by TKlerx** [comment] 2016-08-02 07:48
That solved the problem temporarily, until I opened firefox.
Firefox updated KeePassRPCCopier.exe to v. 1.6.2 and then, Thunderbird does not work anymore.

To me, it seems like the Thunderbird Plugin and the Firefox Plugin are out of sync (using different versions of KeePassRPCCopier).

Any hints to to resolve this?

**Comment by r2evans** [comment] 2016-08-02 15:44
You didn't mention that you were also using (and experiencing problems with) FF, though I could have been clearer that ***every copy*** of `KeePassRPC.plgx` needs to be updated. Thanks for updating your comment accordingly.

**Comment by TKlerx** [comment] 2016-08-04 12:47
Sorry, @r2evans: I was not the one writing the issue.
Just wanted to help others that may read the issue.

But your comment helped alot to solve it. Thanks!

**Comment by r2evans** [comment] 2016-08-04 15:13
Hehe, yeah, an obvious mistake on my part, apologies!

**Closed** 2020-09-03 19:53 UTC
Labels: project-archived
