### ISSUE TITLE
KeePass sometimes asks to save changes to an entry when user has made no modification

### ISSUE THREAD

**Issue by luckyrat** [kee-org/KeeFox#559] opened 2015-10-07 21:17 UTC
As mentioned in part of this thread: https://zohodiscussions.com/keefox/topic/revert-save-credentials-to-old-style

Not sure exactly what causes it but it looks like at least one person's database experiences the issue fairly regularly so it's worth investigating.

I suspect it's somehow related to the modifications made to entries during the upgrade to KeeFox 1.5.

**Comment by dlech** [comment] 2015-10-07 21:38
This happens for me as well with most password entries. I suspect it has to do with the changes in URL matching, but I haven't really dug into it yet either.

**Comment by eToThePiIPower** [comment] 2015-10-10 20:22
I can confirm I have this problem for some entries in my database.

I've run a few tests and it definitely seems related to URL matching. Specifically:
* Protocol (http vs https): Changing the protocol on some sites (eg http://bitbucket.org to https://bitbucket.org) fixed the issue.
* Subdomain: Adding/removing *www* can fix this. Some sites work only with the www subdomain (eg www.barnesandnobel.com), others only without (eg bitbucket.org)

I'm currently working around this issue by cleaning up the URLs in my database for my most-used sites.

**Comment by dlech** [comment] 2015-10-20 18:50
It looks like this might be a duplicate of #37.

**Comment by RizzoV** [comment] 2015-10-20 19:18
> I've just installed KeePass and KeeFox, imported my LastPass database and started using them. When I go on a website where KeePass knows the credentials, imported by LastPass, KeeFox succesfully fills the forms, but after the login it asks if I want to save the password again. The only way to avoid that is to actually save it, through KeeFox, creating a doublet. Is this a my problem or not?

Just tried with Amazon and DropBox, I saved the credentials with KeeFox also if they were already in the database (imported from LastPass and correctly form-filled) and compared the old and the new URL: the only different part is "https://www.amazon.com/ap/[this]" and "https://www.dropbox.com/[this]".

**Comment by luckyrat** [comment] 2015-10-22 21:33
This issue is about the KeePass dialog that appears when you try to close a modified edit entry window, not the KeeFox "Do you want to save this password?" panel.

**Comment by dlech** [comment] 2015-10-22 23:10
My mistake. Is there another newer issue that is the same as #37 or should we reopen that one? My first comment here actually was about seeing problems like #37 as well and not this issue.

**Comment by luckyrat** [comment] 2015-10-25 13:05
Yeah, best to open a new one I think. #37 was about the way we handled this 5 years ago so most of the info in it will not be relevant any more.

**Comment by luckyrat** [comment] 2016-01-09 18:33
There's no clear problem to fix nor a way to reproduce it so I'm not going to prioritise this issue.

**Closed** 2020-09-05 21:52 UTC
Labels: need info, project-archived
